### ISSUE TITLE
본문 설명보다 짧게 생성된 음성 파일 수정

### ISSUE THREAD

**Issue by te6-in** [leecs0503/cose394-docent-chatbot-prototype#48]
> 고려대 박물관 가이드에서 분청사기인화문태호, 금강산도 음성 가이드가 끝까지 재생되지 않는거 같습니다..! 시간 되실 때 한 번 확인해보시면 좋을거 같습니다!!

**Comment by leecs0503** [comment]
음성파일 자체가 짧은걸까요?

**Comment by te6-in** [comment]
> 음성파일 자체가 짧은걸까요?

[그런 것 같습니다](https://github.com/leecs0503/cose394-docent-chatbot-prototype/blob/cb2292d98e9c366e3ea576e5bdf0e9d535976193/public/voices/1/3.mp3)

**Comment by r-4bb1t** [comment]
수정했습니당
